# Generated by Django 3.2.5 on 2021-07-03 04:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField( max_length=128, region=None, null=True),
            preserve_default=False,
        ),
    ]
