# Generated by Django 3.2.5 on 2021-07-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteproduct',
            name='is_favoutire',
            field=models.BooleanField(default=True),
        ),
    ]
