# Generated by Django 3.2.5 on 2021-07-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_alter_favouriteproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteproduct',
            old_name='is_favoutire',
            new_name='is_favourite',
        ),
    ]
